apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-telegram
  labels:
    app: chatgpt-telegram
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-telegram
  template:
    metadata:
      labels:
        app: chatgpt-telegram
    spec:
      containers:
      - name: chatgpt-telegram
        image: loqutus/chatgpt-telegram:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: apikeys
              key: OPENAI_API_KEY
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: apikeys
              key: TELEGRAM_BOT_TOKEN
        - name: ALLOWED_USERS
          valueFrom:
            secretKeyRef:
              name: apikeys
              key: ALLOWED_USERS
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: apikeys
              key: HUGGINGFACE_TOKEN
      ImagePullPolicy: Always
      nodeSelector:
          kubernetes.io/arch: amd64
