apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-tg
  labels:
    app: chatgpt-tg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-tg
  template:
    metadata:
      labels:
        app: chatgpt-tg
    spec:
      containers:
      - name: chatgpt-tg
        image: loqutus/chatgpt-tg:latest
      ImagePullPolicy: Always
